# Generated by Django 5.2.17 on 2026-09-10 22:54

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIBudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(unique=True)),
                ('limit_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('spent_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Бюджет AI за месяц',
                'verbose_name_plural': 'Бюджеты AI по месяцам',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('draft_ru', 'Черновик RU'), ('translate_en', 'Перевод EN'), ('group_events', 'Объединение событий')], max_length=30)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('input_hash', models.CharField(max_length=64)),
                ('instruction_version', models.CharField(default='editorial-v1', max_length=40)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('budget_rejected', 'Отклонено бюджетом')], default='running', max_length=20)),
                ('reserved_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('actual_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('provider_request_id', models.CharField(blank=True, max_length=200)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Запрос к AI',
                'verbose_name_plural': 'Запросы к AI',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['operation', 'input_hash'], name='ai_request_input')],
            },
        ),
    ]
