# Generated by Django 5.2.17 on 2026-09-10 23:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberGeneration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.PositiveBigIntegerField(verbose_name='Telegram user ID')),
                ('telegram_chat_id', models.PositiveBigIntegerField(verbose_name='Telegram chat ID')),
                ('generation', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('interface_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2)),
                ('digest_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2)),
                ('setup_status', models.CharField(choices=[('incomplete', 'Не завершена'), ('complete', 'Завершена')], default='incomplete', max_length=12)),
                ('subscription_status', models.CharField(choices=[('inactive', 'Неактивна'), ('active', 'Активна'), ('paused', 'Пауза')], default='inactive', max_length=12)),
                ('access_status', models.CharField(choices=[('allowed', 'Разрешён'), ('blocked', 'Заблокирован')], default='allowed', max_length=12)),
                ('chat_reachability', models.CharField(choices=[('unknown', 'Неизвестно'), ('reachable', 'Доступен'), ('unreachable', 'Недоступен')], default='unknown', max_length=12)),
                ('dialog_state', models.CharField(choices=[('none', 'Нет'), ('choose_language', 'Выбор языка'), ('choose_collections', 'Выбор подборок'), ('choose_schedule', 'Выбор частоты'), ('review_preferences', 'Проверка настроек'), ('awaiting_feedback', 'Ожидание отзыва'), ('confirm_data_erasure', 'Подтверждение удаления')], default='choose_language', max_length=30)),
                ('privacy_state', models.CharField(choices=[('normal', 'Обычное'), ('erasure_pending', 'Удаление начато')], default='normal', max_length=20)),
                ('automatic_delivery_after', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Поколение подписчика',
                'verbose_name_plural': 'Подписчики',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('telegram_user_id', 'generation'), name='unique_subscriber_generation'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('telegram_user_id',), name='unique_current_subscriber')],
            },
        ),
        migrations.CreateModel(
            name='PreferenceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('interface_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('digest_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=True)),
                ('schedule_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriber_preferences', to='scheduling.schedulerevision')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preference_revisions', to='subscriptions.subscribergeneration')),
            ],
            options={
                'verbose_name': 'Редакция настроек',
                'verbose_name_plural': 'Редакции настроек',
                'ordering': ['subscriber', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriber_selections', to='catalog.collection')),
                ('preference_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_collections', to='subscriptions.preferencerevision')),
            ],
            options={
                'verbose_name': 'Выбранная подборка',
                'verbose_name_plural': 'Выбранные подборки',
                'ordering': ['collection__sort_order', 'collection_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='preferencerevision',
            constraint=models.UniqueConstraint(fields=('subscriber', 'revision'), name='unique_preference_revision'),
        ),
        migrations.AddConstraint(
            model_name='preferencerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('subscriber',), name='unique_current_preferences'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncollection',
            constraint=models.UniqueConstraint(fields=('preference_revision', 'collection'), name='unique_preference_collection'),
        ),
    ]
