# Generated by Django 5.2.17 on 2026-09-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribergeneration',
            constraint=models.CheckConstraint(condition=models.Q(('setup_status', 'complete'), ('subscription_status', 'inactive'), _connector='OR'), name='incomplete_subscriber_is_inactive'),
        ),
        migrations.AddConstraint(
            model_name='subscribergeneration',
            constraint=models.CheckConstraint(condition=models.Q(('privacy_state', 'erasure_pending'), ('subscription_status', 'active'), _negated=True), name='erasure_pending_is_not_active'),
        ),
    ]
