# Generated by Django 5.2.17 on 2026-09-10 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscribergeneration_incomplete_subscriber_is_inactive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('interface_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('digest_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('collection_ids', models.JSONField(blank=True, default=list)),
                ('schedule_id', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_draft', to='subscriptions.subscribergeneration')),
            ],
            options={
                'verbose_name': 'Черновик настроек',
                'verbose_name_plural': 'Черновики настроек',
            },
        ),
    ]
