# Generated by Django 5.2.17 on 2026-09-11 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_preferencedraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureTombstone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_generation', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Guard удаления',
                'verbose_name_plural': 'Guard удаления после восстановления',
            },
        ),
        migrations.AlterField(
            model_name='subscribergeneration',
            name='privacy_state',
            field=models.CharField(choices=[('normal', 'Обычное'), ('erasure_pending', 'Удаление начато'), ('erased', 'Обезличено')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='ErasureRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Ожидает подтверждения'), ('accepted', 'Принято'), ('processing', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено до подтверждения')], default='pending_confirmation', max_length=24)),
                ('confirmation_expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests', to='subscriptions.subscribergeneration')),
            ],
            options={
                'verbose_name': 'Запрос удаления',
                'verbose_name_plural': 'Запросы удаления данных',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending_confirmation', 'accepted', 'processing'])), fields=('subscriber',), name='unique_active_erasure_request')],
            },
        ),
    ]
