# Generated by Django 5.2.17 on 2026-09-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ("name_ru", models.CharField(max_length=240, verbose_name="Название RU")),
                ("name_en", models.CharField(max_length=240, verbose_name="Название EN")),
                ("description_ru", models.TextField(blank=True, verbose_name="Описание RU")),
                ("description_en", models.TextField(blank=True, verbose_name="Описание EN")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("news", "Новости"),
                            ("analysis_digest", "Аналитика"),
                            ("video_digest", "Видео — следующая версия"),
                        ],
                        default="news",
                        max_length=30,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "release_target",
                    models.CharField(
                        choices=[("v1", "Первая версия"), ("later_version", "Следующая версия")],
                        default="v1",
                        max_length=20,
                        verbose_name="Версия",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="Активна")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Подборка",
                "verbose_name_plural": "Подборки",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="OriginGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=240, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Группа происхождения",
                "verbose_name_plural": "Группы происхождения",
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=240, verbose_name="Название")),
                ("definition", models.JSONField(verbose_name="Правило хранения")),
            ],
            options={
                "verbose_name": "Профиль хранения",
                "verbose_name_plural": "Профили хранения",
            },
        ),
        migrations.CreateModel(
            name="PublisherProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=240, verbose_name="Редакция или автор")),
                ("role", models.CharField(max_length=50, verbose_name="Роль")),
                ("default_language", models.CharField(max_length=12, verbose_name="Язык")),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "research_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сведения исследования"
                    ),
                ),
                (
                    "origin_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.origingroup",
                        verbose_name="Происхождение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль редакции",
                "verbose_name_plural": "Профили редакций",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.SlugField(max_length=120, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("website", "Сайт"), ("telegram", "Telegram")],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("url", models.URLField(max_length=2000, unique=True, verbose_name="Адрес")),
                ("input_language", models.CharField(max_length=12, verbose_name="Язык")),
                ("is_active", models.BooleanField(default=False, verbose_name="Активен")),
                (
                    "access_review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Не проверено"),
                            ("approved", "Способ подтверждён"),
                            ("denied", "Недоступен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Проверка использования",
                    ),
                ),
                (
                    "access_review_note",
                    models.TextField(blank=True, verbose_name="Способ использования и основание"),
                ),
                (
                    "collection_check_status",
                    models.CharField(
                        choices=[
                            ("not_connected", "Не подключён"),
                            ("verified", "Проверен"),
                            ("failed", "Ошибка"),
                        ],
                        default="not_connected",
                        max_length=30,
                        verbose_name="Проверка сборщика",
                    ),
                ),
                (
                    "preferred_adapter",
                    models.CharField(blank=True, max_length=100, verbose_name="Адаптер"),
                ),
                (
                    "preferred_feed_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="RSS"),
                ),
                (
                    "technical_status",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Результат исследования"
                    ),
                ),
                (
                    "research_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сведения исследования"
                    ),
                ),
                (
                    "origin_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.origingroup",
                        verbose_name="Происхождение",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.publisherprofile",
                        verbose_name="Редакция",
                    ),
                ),
                (
                    "retention_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.retentionpolicy",
                        verbose_name="Хранение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
            },
        ),
        migrations.CreateModel(
            name="SourceCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Включён в подборку"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("pilot", "Пилот"), ("reserve", "Резерв")],
                        default="reserve",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        default="topic_filtered_news", max_length=80, verbose_name="Назначение"
                    ),
                ),
                ("topic_filter", models.TextField(blank=True, verbose_name="Тематический фильтр")),
                ("editorial_note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.collection",
                        verbose_name="Подборка",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.source",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь источника и подборки",
                "verbose_name_plural": "Источники в подборках",
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="sources",
            field=models.ManyToManyField(
                related_name="collections", through="catalog.SourceCollection", to="catalog.source"
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_active", False),
                    models.Q(
                        ("access_review_status", "approved"),
                        ("collection_check_status", "verified"),
                        models.Q(("access_review_note", ""), _negated=True),
                        models.Q(("preferred_adapter", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="source_activation_requires_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecollection",
            constraint=models.UniqueConstraint(
                fields=("source", "collection"), name="unique_source_collection"
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_active", False),
                    models.Q(
                        ("release_target", "v1"), models.Q(("kind", "video_digest"), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="active_collection_requires_v1_text",
            ),
        ),
    ]
