# Generated by Django 5.2.17 on 2026-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='routing_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Список слов или фраз для автоматического назначения событий в подборку.', verbose_name='Ключевые слова маршрутизации'),
        ),
    ]
