# Generated by Django 5.2.17 on 2026-09-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ("name_ru", models.CharField(max_length=200, verbose_name="Название RU")),
                ("name_en", models.CharField(max_length=200, verbose_name="Название EN")),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow", max_length=80, verbose_name="Часовой пояс"
                    ),
                ),
                (
                    "recurrence_kind",
                    models.CharField(
                        choices=[("daily", "Ежедневно"), ("weekly", "Еженедельно")],
                        default="daily",
                        max_length=10,
                        verbose_name="Повторение",
                    ),
                ),
                ("local_times", models.JSONField(default=list, verbose_name="Время отправки")),
                (
                    "iso_weekdays",
                    models.JSONField(blank=True, default=list, verbose_name="Дни недели"),
                ),
                (
                    "preparation_lead_minutes",
                    models.PositiveSmallIntegerField(default=10, verbose_name="Подготовка за, мин"),
                ),
                (
                    "late_delivery_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Допустимое опоздание, мин"
                    ),
                ),
                (
                    "visible_to_new_subscribers",
                    models.BooleanField(default=False, verbose_name="Показывать новым подписчикам"),
                ),
                (
                    "delivery_enabled",
                    models.BooleanField(default=False, verbose_name="Рассылка разрешена"),
                ),
                (
                    "effective_from",
                    models.DateTimeField(blank=True, null=True, verbose_name="Действует с"),
                ),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="Порядок")),
                (
                    "revision",
                    models.PositiveIntegerField(default=1, editable=False, verbose_name="Редакция"),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписания",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(verbose_name="Редакция")),
                ("rule", models.JSONField(verbose_name="Правило")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="scheduling.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Редакция расписания",
                "verbose_name_plural": "Редакции расписаний",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule", "number"), name="unique_schedule_revision"
                    )
                ],
            },
        ),
    ]
