# Generated by Django 5.2.17 on 2026-09-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(verbose_name='Время отправки')),
                ('window_start', models.DateTimeField(verbose_name='Начало окна')),
                ('window_end', models.DateTimeField(verbose_name='Конец окна')),
                ('preparation_at', models.DateTimeField(verbose_name='Начать подготовку')),
                ('delivery_deadline', models.DateTimeField(verbose_name='Крайний срок доставки')),
                ('state', models.CharField(choices=[('planned', 'Запланирован'), ('preparing', 'Подготавливается'), ('prepared', 'Подготовлен'), ('closed', 'Закрыт'), ('failed', 'Ошибка')], default='planned', max_length=15, verbose_name='Состояние')),
                ('preparation_summary', models.JSONField(blank=True, default=dict, verbose_name='Результат подготовки')),
                ('schedule_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='scheduling.schedulerevision')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'verbose_name_plural': 'Слоты расписаний',
                'ordering': ['scheduled_at'],
                'constraints': [models.UniqueConstraint(fields=('schedule_revision', 'scheduled_at'), name='unique_schedule_slot')],
            },
        ),
    ]
