# Generated by Django 5.2.17 on 2026-09-11 12:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('collect_source', 'Собрать источник'), ('suggest_groupings', 'Предложить группировки'), ('prepare_schedule_slot', 'Подготовить слот рассылки'), ('purge_source_text', 'Удалить истёкшие тексты')], max_length=40, verbose_name='Тип')),
                ('contract_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('retry_wait', 'Ожидает повтора'), ('done', 'Выполнено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=15, verbose_name='Состояние')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_owner', models.CharField(blank=True, max_length=120)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Фоновое задание',
                'verbose_name_plural': 'Фоновые задания',
                'ordering': ['next_attempt_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('published', 'Передано брокеру'), ('consumed', 'Принято исполнителем'), ('failed', 'Ошибка публикации')], default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('broker_message_id', models.CharField(blank=True, max_length=100)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='operations.backgroundjob')),
            ],
            options={
                'verbose_name': 'Запись outbox',
                'verbose_name_plural': 'Transactional outbox',
                'ordering': ['next_attempt_at', 'created_at'],
            },
        ),
    ]
