# Generated by Django 5.2.17 on 2026-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='kind',
            field=models.CharField(choices=[('collect_source', 'Собрать источник'), ('suggest_groupings', 'Предложить группировки'), ('discover_editorial_candidates', 'Подготовить редакторский отбор'), ('generate_event_cards', 'Создать карточки RU/EN'), ('build_editorial_editions', 'Собрать выпуски RU/EN'), ('prepare_schedule_slot', 'Подготовить слот рассылки'), ('purge_source_text', 'Удалить истёкшие тексты')], max_length=40, verbose_name='Тип'),
        ),
    ]
