# Generated by Django 5.2.17 on 2026-09-11 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_backgroundjob_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=160)),
                ('lease_expires_at', models.DateTimeField()),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Аренда процесса',
                'verbose_name_plural': 'Процессы и heartbeat',
            },
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='kind',
            field=models.CharField(choices=[('collect_source', 'Собрать источник'), ('suggest_groupings', 'Предложить группировки'), ('discover_editorial_candidates', 'Подготовить редакторский отбор'), ('generate_event_cards', 'Создать карточки RU/EN'), ('build_editorial_editions', 'Собрать выпуски RU/EN'), ('erase_subscriber', 'Удалить данные подписчика'), ('purge_privacy_records', 'Очистить истёкшие privacy-записи'), ('prepare_schedule_slot', 'Подготовить слот рассылки'), ('purge_source_text', 'Удалить истёкшие тексты')], max_length=40, verbose_name='Тип'),
        ),
    ]
