# Generated by Django 5.2.17 on 2026-09-11 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_processlease_alter_backgroundjob_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.CharField(default=uuid.uuid4, editable=False, max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('database', 'База данных'), ('erasure_guard', 'Реестр удалений')], max_length=24, verbose_name='Состав копии')),
                ('database_backend', models.CharField(max_length=24)),
                ('storage_class', models.CharField(choices=[('local_training', 'Локальная учебная копия'), ('external', 'Внешнее')], max_length=24, verbose_name='Хранилище')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('succeeded', 'Готово'), ('failed', 'Ошибка'), ('expired', 'Файл удалён по сроку')], default='running', max_length=12, verbose_name='Состояние')),
                ('encrypted', models.BooleanField(default=False)),
                ('artifact_name', models.CharField(blank=True, max_length=240)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreDrill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка')], default='running', max_length=12, verbose_name='Состояние')),
                ('isolated', models.BooleanField(default=True, editable=False)),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_drills', to='operations.backuprun')),
            ],
            options={
                'verbose_name': 'Проверка восстановления',
                'verbose_name_plural': 'Проверки восстановления',
                'ordering': ['-created_at'],
            },
        ),
    ]
