# Generated by Django 5.2.17 on 2026-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_backgroundjob_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySafetyState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='global', editable=False, max_length=24, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('blocked', 'Заблокирована'), ('ready', 'Разрешена')], default='blocked', max_length=12, verbose_name='Состояние доставки')),
                ('applied_guard_sha256', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Безопасность доставки',
                'verbose_name_plural': 'Безопасность доставки',
            },
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='kind',
            field=models.CharField(choices=[('collect_source', 'Собрать источник'), ('suggest_groupings', 'Предложить группировки'), ('discover_editorial_candidates', 'Подготовить редакторский отбор'), ('generate_event_cards', 'Создать карточки RU/EN'), ('build_editorial_editions', 'Собрать выпуски RU/EN'), ('erase_subscriber', 'Удалить данные подписчика'), ('purge_privacy_records', 'Очистить истёкшие privacy-записи'), ('create_database_backup', 'Создать резервную копию базы'), ('purge_backup_artifacts', 'Удалить истёкшие файлы копий'), ('export_erasure_guard', 'Экспортировать реестр удалений'), ('prepare_schedule_slot', 'Подготовить слот рассылки'), ('purge_source_text', 'Удалить истёкшие тексты')], max_length=40, verbose_name='Тип'),
        ),
    ]
