# Generated by Django 5.2.17 on 2026-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_deliverysafetystate_alter_backgroundjob_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='kind',
            field=models.CharField(choices=[('collect_source', 'Собрать источник'), ('suggest_groupings', 'Предложить группировки'), ('discover_editorial_candidates', 'Подготовить редакторский отбор'), ('automatic_digest_cycle', 'Автоматически собрать и опубликовать выпуск'), ('generate_event_cards', 'Создать карточки RU/EN'), ('build_editorial_editions', 'Собрать выпуски RU/EN'), ('erase_subscriber', 'Удалить данные подписчика'), ('purge_privacy_records', 'Очистить истёкшие privacy-записи'), ('create_database_backup', 'Создать резервную копию базы'), ('purge_backup_artifacts', 'Удалить истёкшие файлы копий'), ('export_erasure_guard', 'Экспортировать реестр удалений'), ('prepare_schedule_slot', 'Подготовить слот рассылки'), ('purge_source_text', 'Удалить истёкшие тексты')], max_length=40, verbose_name='Тип'),
        ),
    ]
