# Generated by Django 5.2.17 on 2026-09-10 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('working_title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('proposed', 'Предложено'), ('review', 'На проверке'), ('approved', 'Подтверждено'), ('held', 'Отложено'), ('merged', 'Объединено')], default='proposed', max_length=20)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Основной материал'), ('corroborates', 'Подтверждает'), ('context', 'Контекст'), ('contradicts', 'Противоречит')], default='corroborates', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='editorial.event')),
                ('publication_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_memberships', to='ingestion.publicationversion')),
            ],
            options={
                'verbose_name': 'Материал события',
                'verbose_name_plural': 'Материалы события',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='versions',
            field=models.ManyToManyField(related_name='events', through='editorial.EventMembership', to='ingestion.publicationversion'),
        ),
        migrations.CreateModel(
            name='EventCardRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_key', models.CharField(max_length=160)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('revision', models.PositiveIntegerField()),
                ('editorial_state', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('approved', 'Утверждено'), ('published', 'Опубликовано'), ('held', 'Отложено')], default='draft', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('citation_membership_ids', models.JSONField(default=list)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('change_note', models.CharField(blank=True, max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_revisions', to='editorial.event')),
                ('source_ru_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='editorial.eventcardrevision')),
            ],
            options={
                'verbose_name': 'Редакция карточки',
                'verbose_name_plural': 'Редакции карточек',
                'ordering': ['event', 'slot_key', 'language', 'revision'],
                'constraints': [models.UniqueConstraint(fields=('event', 'slot_key', 'language', 'revision'), name='unique_event_card_revision'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('event', 'slot_key', 'language'), name='unique_current_event_card'), models.CheckConstraint(condition=models.Q(models.Q(('language', 'ru'), ('source_ru_revision__isnull', True)), models.Q(('language', 'en'), ('source_ru_revision__isnull', False)), _connector='OR'), name='translation_requires_ru_revision')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventmembership',
            constraint=models.UniqueConstraint(fields=('event', 'publication_version'), name='unique_event_version'),
        ),
    ]
