# Generated by Django 5.2.17 on 2026-09-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcardrevision',
            name='evidence_membership_ids',
            field=models.JSONField(default=list),
        ),
    ]
