# Generated by Django 5.2.17 on 2026-09-10 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('editorial', '0002_eventcardrevision_evidence_membership_ids'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='catalog.collection')),
                ('schedule_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='scheduling.schedulerevision')),
            ],
            options={
                'verbose_name': 'Выпуск',
                'verbose_name_plural': 'Выпуски',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='EditionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('revision', models.PositiveIntegerField()),
                ('editorial_state', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('approved', 'Утверждено'), ('published', 'Опубликовано'), ('held', 'Отложено')], default='draft', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('item_snapshot', models.JSONField(default=list)),
                ('rendered_parts', models.JSONField(default=list)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('change_note', models.CharField(blank=True, max_length=500)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='editorial.edition')),
                ('source_ru_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='editorial.editionrevision')),
            ],
            options={
                'verbose_name': 'Редакция выпуска',
                'verbose_name_plural': 'Редакции выпусков',
                'ordering': ['edition', 'language', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='EditionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('main', 'Главная тема'), ('additional', 'Дополнительно')], max_length=20)),
                ('position', models.PositiveSmallIntegerField()),
                ('card_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edition_items', to='editorial.eventcardrevision')),
                ('edition_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='editorial.editionrevision')),
            ],
            options={
                'verbose_name': 'История выпуска',
                'verbose_name_plural': 'Истории выпуска',
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='edition',
            constraint=models.UniqueConstraint(fields=('collection', 'schedule_revision', 'scheduled_at'), name='unique_collection_schedule_slot'),
        ),
        migrations.AddConstraint(
            model_name='editionrevision',
            constraint=models.UniqueConstraint(fields=('edition', 'language', 'revision'), name='unique_edition_revision'),
        ),
        migrations.AddConstraint(
            model_name='editionrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('edition', 'language'), name='unique_current_edition_revision'),
        ),
        migrations.AddConstraint(
            model_name='editionrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('language', 'ru'), ('source_ru_revision__isnull', True)), models.Q(('language', 'en'), ('source_ru_revision__isnull', False)), _connector='OR'), name='edition_translation_requires_ru'),
        ),
        migrations.AddConstraint(
            model_name='editionitem',
            constraint=models.UniqueConstraint(fields=('edition_revision', 'position'), name='unique_edition_position'),
        ),
        migrations.AddConstraint(
            model_name='editionitem',
            constraint=models.UniqueConstraint(fields=('edition_revision', 'card_revision'), name='unique_edition_card'),
        ),
    ]
