# Generated by Django 5.2.17 on 2026-09-10 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_edition_editionrevision_editionitem_and_more'),
        ('ingestion', '0003_alter_publicationversion_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reasons', models.JSONField(default=dict)),
                ('algorithm_version', models.CharField(default='lexical-v1', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('accepted', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('first_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_suggestions_as_first', to='ingestion.publicationversion')),
                ('second_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_suggestions_as_second', to='ingestion.publicationversion')),
            ],
            options={
                'verbose_name': 'Предложение объединения',
                'verbose_name_plural': 'Предложения объединения',
                'ordering': ['-score', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('first_version', 'second_version', 'algorithm_version'), name='unique_grouping_pair_version'), models.CheckConstraint(condition=models.Q(('first_version_id__lt', models.F('second_version_id'))), name='ordered_grouping_pair')],
            },
        ),
    ]
