# Generated by Django 5.2.17 on 2026-09-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('editorial', '0004_groupingsuggestion'),
        ('scheduling', '0002_scheduleslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='review_note',
            field=models.TextField(blank=True, help_text='Обязательно при ручном допуске события с одним происхождением.'),
        ),
        migrations.CreateModel(
            name='EditorialSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оценки'), ('main', 'Главная тема'), ('additional', 'Дополнительно'), ('excluded', 'Исключено'), ('held', 'Отложено')], default='pending', max_length=15)),
                ('impact', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('novelty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timeliness', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('corroboration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weighted_score', models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editorial_selections', to='catalog.collection')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='editorial.event')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='scheduling.scheduleslot')),
            ],
            options={
                'verbose_name': 'Отбор сюжета',
                'verbose_name_plural': 'Редакторский отбор',
                'ordering': ['collection__sort_order', '-weighted_score', 'event_id'],
                'constraints': [models.UniqueConstraint(fields=('slot', 'collection', 'event'), name='unique_editorial_selection')],
            },
        ),
    ]
