# Generated by Django 5.2.17 on 2026-09-13 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('editorial', '0005_event_review_note_editorialselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCollectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.CharField(choices=[('editor', 'Редактор'), ('rule', 'Правило'), ('ai', 'AI-классификатор')], default='editor', max_length=20)),
                ('rationale', models.TextField(verbose_name='Основание')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_assignments', to='catalog.collection')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_assignments', to='editorial.event')),
            ],
            options={
                'verbose_name': 'Назначение события в подборку',
                'verbose_name_plural': 'Назначения событий в подборки',
                'constraints': [models.UniqueConstraint(fields=('event', 'collection'), name='unique_event_collection_assignment')],
            },
        ),
    ]
