# Generated by Django 5.2.17 on 2026-09-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFetchState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='fetch_state', serialize=False, to='catalog.source')),
                ('etag', models.CharField(blank=True, max_length=500)),
                ('last_modified', models.CharField(blank=True, max_length=500)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never', 'Не запускался'), ('success', 'Успешно'), ('not_modified', 'Без изменений'), ('failed', 'Ошибка')], default='never', max_length=30)),
                ('last_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Состояние получения',
                'verbose_name_plural': 'Состояния получения',
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('not_modified', 'Без изменений'), ('failed', 'Ошибка')], default='running', max_length=20)),
                ('requested_limit', models.PositiveSmallIntegerField(default=10)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('new_version_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_runs', to='catalog.source')),
            ],
            options={
                'verbose_name': 'Запуск получения',
                'verbose_name_plural': 'Запуски получения',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=1000)),
                ('canonical_url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='catalog.source')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='PublicationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('language', models.CharField(max_length=12)),
                ('content_scope', models.CharField(choices=[('full_article', 'Полный извлечённый текст'), ('feed_excerpt', 'Фрагмент из ленты'), ('page_extract', 'Текст страницы')], max_length=30)),
                ('fetched_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('extraction_metadata', models.JSONField(blank=True, default=dict)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='ingestion.publication')),
            ],
            options={
                'verbose_name': 'Версия публикации',
                'verbose_name_plural': 'Версии публикаций',
                'ordering': ['publication', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['source', '-published_at'], name='publication_source_time'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_item'),
        ),
        migrations.AddIndex(
            model_name='publicationversion',
            index=models.Index(fields=['expires_at'], name='publication_version_expiry'),
        ),
        migrations.AddConstraint(
            model_name='publicationversion',
            constraint=models.UniqueConstraint(fields=('publication', 'number'), name='unique_publication_version_number'),
        ),
        migrations.AddConstraint(
            model_name='publicationversion',
            constraint=models.UniqueConstraint(fields=('publication', 'content_hash'), name='unique_publication_content_hash'),
        ),
    ]
