# Generated by Django 5.2.17 on 2026-09-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationversion',
            name='purge_reason',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='publicationversion',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
