# Generated by Django 5.2.17 on 2026-09-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_publicationversion_purge_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationversion',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
