# Generated by Django 5.2.17 on 2026-09-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('ingestion', '0003_alter_publicationversion_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProbeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Доступен'), ('failed', 'Ошибка')], default='running', max_length=12)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_url', models.URLField(blank=True, max_length=2000)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('response_bytes', models.PositiveIntegerField(default=0)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('dated_item_count', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='probe_runs', to='catalog.source')),
            ],
            options={
                'verbose_name': 'Проверка источника',
                'verbose_name_plural': 'Проверки источников',
                'ordering': ['-started_at'],
            },
        ),
    ]
