# Generated by Django 5.2.17 on 2026-09-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_sourceproberun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationversion',
            name='content_scope',
            field=models.CharField(choices=[('full_article', 'Полный извлечённый текст'), ('feed_excerpt', 'Фрагмент из ленты'), ('feed_title', 'Только заголовок ленты'), ('page_extract', 'Текст страницы')], max_length=30),
        ),
    ]
