# Generated by Django 5.2.17 on 2026-09-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_alter_publicationversion_content_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceproberun',
            name='article_attempted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourceproberun',
            name='article_success_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
