# Generated by Django 5.2.17 on 2026-09-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_sourceproberun_article_attempted_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefetchstate',
            name='last_external_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationversion',
            name='content_scope',
            field=models.CharField(choices=[('full_article', 'Полный извлечённый текст'), ('feed_excerpt', 'Фрагмент из ленты'), ('feed_title', 'Только заголовок ленты'), ('page_extract', 'Текст страницы'), ('telegram_post', 'Публичный пост Telegram')], max_length=30),
        ),
    ]
