# Generated by Django 5.2.17 on 2026-09-10 23:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('automatic', 'Автоматическая'), ('manual', 'По запросу'), ('correction', 'Исправление')], max_length=15)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена'), ('unknown', 'Результат неизвестен')], default='pending', max_length=15)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(choices=[('sent', 'Отправлена'), ('temporary_failure', 'Временная ошибка'), ('permanent_failure', 'Постоянная ошибка'), ('unknown', 'Результат неизвестен')], max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('provider_request_id', models.CharField(blank=True, max_length=200)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Попытка доставки',
                'verbose_name_plural': 'Попытки доставки',
                'ordering': ['part', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition_revision_ids', models.JSONField(default=list)),
                ('kept_occurrences', models.JSONField(default=list)),
                ('omitted_occurrences', models.JSONField(blank=True, default=list)),
                ('missing_collection_ids', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('frozen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Манифест отправки',
                'verbose_name_plural': 'Манифесты отправок',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_number', models.PositiveSmallIntegerField()),
                ('body', models.TextField()),
                ('body_hash', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_flight', 'Передана Telegram'), ('sent', 'Отправлена'), ('retry_wait', 'Ожидает повтора'), ('failed', 'Ошибка'), ('cancelled', 'Отменена'), ('unknown', 'Результат неизвестен')], default='pending', max_length=15)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Часть отправки',
                'verbose_name_plural': 'Части отправки',
                'ordering': ['delivery', 'part_number'],
            },
        ),
    ]
