# Generated by Django 5.2.17 on 2026-09-10 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='preference_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='subscriptions.preferencerevision'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='schedule_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='scheduling.schedulerevision'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='subscriber_generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='subscriptions.subscribergeneration'),
        ),
        migrations.AddField(
            model_name='deliverymanifest',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manifest', to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='deliverypart',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='delivery.deliverypart'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'automatic')), fields=('subscriber_generation', 'schedule_revision', 'scheduled_at', 'kind'), name='unique_automatic_delivery_slot'),
        ),
        migrations.AddConstraint(
            model_name='deliverypart',
            constraint=models.UniqueConstraint(fields=('delivery', 'part_number'), name='unique_delivery_part'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('part', 'attempt_number'), name='unique_delivery_attempt'),
        ),
    ]
