# Generated by Django 5.2.17 on 2026-09-10 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypart',
            name='next_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
