# Generated by Django 5.2.17 on 2026-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverypart_next_attempt_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypart',
            name='in_flight_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
