# Generated by Django 5.2.17 on 2026-09-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeedSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=120, verbose_name="Файл")),
                ("sha256", models.CharField(max_length=64, verbose_name="SHA-256")),
                ("payload", models.JSONField(verbose_name="Исходные данные")),
            ],
            options={
                "verbose_name": "Снимок начальных данных",
                "verbose_name_plural": "Снимки начальных данных",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("filename", "sha256"), name="unique_seed_snapshot"
                    )
                ],
            },
        ),
    ]
