# Generated by Django 5.2.17 on 2026-09-10 23:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdateReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_id', models.BigIntegerField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('update_kind', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('processed', 'Обработано'), ('ignored', 'Пропущено')], default='processing', max_length=15)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Полученное обновление Telegram',
                'verbose_name_plural': 'Полученные обновления Telegram',
                'ordering': ['-update_id'],
            },
        ),
        migrations.CreateModel(
            name='BotReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField()),
                ('callback_query_id', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('keyboard', models.JSONField(blank=True, default=list)),
                ('parse_mode', models.CharField(default='HTML', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_flight', 'Передан Telegram'), ('sent', 'Отправлен'), ('retry_wait', 'Ожидает повтора'), ('failed', 'Ошибка'), ('unknown', 'Результат неизвестен')], default='pending', max_length=15)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reply', to='telegram_bot.telegramupdatereceipt')),
            ],
            options={
                'verbose_name': 'Ответ бота',
                'verbose_name_plural': 'Ответы бота',
                'ordering': ['created_at'],
            },
        ),
    ]
