# Generated by Django 5.2.17 on 2026-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_botreply_in_flight_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='botreply',
            name='edit_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
